### ISSUE TITLE
Possibility to indicate group on a single line only

### ISSUE THREAD

**Issue by georgesguigui** [no-stack-dub-sack/apexdox-vs-code#28]
Hi,

If @group tag of apex class is on several lines, only the latest line is displayed in sidebar menu.
Moreover, if another non recognized tag is indicated, it is considered to be part of the group name.
In example below, because following tag are not recognized:
@Last Modified By 
@Last Modified On
@Modification Log
The group name that appears in navigation menu is: "1.0       02/05/2020      DUN          Initial Version"

A workaround is to put @group tag before @description (which is quite logical, but this is not the default setting for Salesforce Documenter VS Code plugin).

/**
 * @Description         xxxxxx
 * @Author              xxxx
 * @Group               Group Name
 * @Last Modified By    : GGU
 * @Last Modified On    : 06/10/2020
 * @Modification Log
 * Ver       Date            Author       Modification
 * 1.0       02/05/2020      DUN          Initial Version
 **/

**Comment by no-stack-dub-sack** [comment]
@georgesguigui It seems like you're perhaps using another VS Code plugin to help document Apex files which contain tags the Apexdox does not support. Ideally these tags should just be ignored, but it may be that the way the algorithm works only starts a new block when a new recognized tag is encountered. Feel free to open a PR if you'd like to see this issue solved (the problem is likely in [this file](https://github.com/no-stack-dub-sack/apexdox-vs-code/blob/master/src/common/models/ApexModel.ts), probably [right around here](https://github.com/no-stack-dub-sack/apexdox-vs-code/blob/master/src/common/models/ApexModel.ts#L153) somewhere), but in the meantime it seems you have a decent workaround in place. In general, behavior may be unpredictable if you're using tags that are unsupported by the documentation engine.

**Comment by no-stack-dub-sack** [comment]
closing as stale. @georgesguigui please feel free to reopen if you need additional help.
